/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzh_ndkdemo_jni_JniUtil */

#ifndef _Included_com_lzh_ndkdemo_jni_JniUtil
#define _Included_com_lzh_ndkdemo_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzh_ndkdemo_jni_JniUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzh_ndkdemo_jni_JniUtil_test
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
